version: '3.8'

services:
  mentors:
    build:
      context: .
      dockerfile: apps/mentors/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps/mentors:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - redis

  mentees:
    build:
      context: .
      dockerfile: apps/mentees/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - ./apps/mentees:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
